apiVersion: v1
kind: ServiceAccount
metadata:
  name: validation-runner
  namespace: {{ include "validation-jobs.namespace" . }}
  labels:
    {{- include "validation-jobs.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: validation-runner
  namespace: {{ include "validation-jobs.namespace" . }}
  labels:
    {{- include "validation-jobs.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: validation-runner
  namespace: {{ include "validation-jobs.namespace" . }}
  labels:
    {{- include "validation-jobs.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: validation-runner
    namespace: {{ include "validation-jobs.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: validation-runner
