apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-api
  namespace: enterprise-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-api
  template:
    metadata:
      labels:
        app: enterprise-api
    spec:
      containers:
      - name: enterprise-api
        image: ind-mlops-python-service:latest
        command: ["python", "-m", "services.enterprise_api"]
        env:
        - name: TIMESCALE_HOST
          value: "timescale-svc.fog-tier.svc.cluster.local"
        - name: TIMESCALE_PORT
          value: "5432"
        - name: TIMESCALE_ADMIN_USER
          value: "admin"
        - name: TIMESCALE_ADMIN_PASSWORD
          value: "password123"
        - name: FACTORY_DB_NAME
          value: "factory_db"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-svc.cloud-tier.svc.cluster.local:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio-svc.fog-tier.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "admin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "password123"
        - name: MQTT_HOST
          value: "mosquitto-svc.edge-tier.svc.cluster.local"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-svc.edge-tier.svc.cluster.local:9092"
        - name: INDUSTRIAL_SHARED_SECRET
          value: "industrial-mlops-shared-secret"
        - name: ENTERPRISE_API_KEY
          value: "enterprise-demo-key"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-api-svc
  namespace: enterprise-tier
spec:
  selector:
    app: enterprise-api
  ports:
    - port: 8085
      targetPort: 8085
