apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ include "edge-tier.namespace" . }}
  labels:
    {{- include "edge-tier.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: {{ include "edge-tier.namespace" . }}
  labels:
    app: mosquitto
    {{- include "edge-tier.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        {{- include "edge-tier.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mosquitto
          image: {{ .Values.images.mosquitto | quote }}
          command: ["/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf"]
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: config-vol
              mountPath: /mosquitto-no-auth.conf
              subPath: mosquitto.conf
      volumes:
        - name: config-vol
          configMap:
            name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-svc
  namespace: {{ include "edge-tier.namespace" . }}
  labels:
    {{- include "edge-tier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.mosquitto.type }}
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
    - name: ws
      port: 9001
